services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
